---
- name: Create Node Exporter directory
  ansible.builtin.file:
    path: /opt/node_exporter
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Node Exporter docker-compose.yml
  ansible.builtin.template:
    src: node-exporter-compose.yml.j2
    dest: /opt/node_exporter/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Start Node Exporter
  community.docker.docker_compose_v2:
    project_src: /opt/node_exporter
    state: present
  when: docker_services_enabled | bool
